config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tables, only: [:new, :edit, :index, :destroy, :update, :create]

  get '/user/tables', to: 'tables#user_index', as: 'user_index'
  root to: "tables#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scraper.rb
require 'nokogiri'
require 'open-uri'

class Scraper

  def scrape_pingpong_tables
  @tables_new = []

    num_pages_to_scrape = 290
    count = 0
    webcount = 0

    # mech_page = @agent.get("https://pingpongmap.net/index.php?typ=list&zeig=#{webcount}")

  while(num_pages_to_scrape > count)
    url = "https://pingpongmap.net/index.php?typ=list&zeig=#{webcount}"
    html_file = open(url).read
    html_doc = Nokogiri::HTML(html_file)


    html_doc.search('.list_item .inner').each do |link|

    @tables_new << {location: link.content.strip.split("\n")[2].strip, description: link.content.strip.split("\n")[1].strip}
    end

    webcount += 30
    count += 1

  end
  @tables_new
  end
end

# scrape = Scraper.new
# scrape.scrape_pingpong_tables

app/models/table.rb
class Table < ApplicationRecord
  has_one_attached :table_photo, dependent: :destroy
  validates :description, presence: true, length: { minimum: 10 }
  validates :location, presence: true, length: { minimum: 10 }

  after_commit :add_default_cover, on: [:create, :update]

   def self.create_from_collection(tables_new)
      tables_new.each do |table_hash|
        Table.find_or_create_by(table_hash)
        sleep(0.3)
    end
  end

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def coordinates
    [longitude, latitude]
  end

  def to_feature
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": coordinates
      },
      "properties": {
        "table_id": id,
        "info_window": ApplicationController.new.render_to_string(
          partial: "tables/info_window",
          locals: { table: self }
        )
      }
    }

  end

  private

  def add_default_cover
    unless table_photo.attached?
      file = URI.open("https://res.cloudinary.com/dw0fvtaxe/image/upload/v1638271635/development/1h38rufpqlj2bhamv1sgmasnvym5.jpg")
    self.table_photo.attach(io: file, filename: 'default-image.jpg')
  end

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def index
    @tables = Table.where( "location LIKE ?", "% Berlin%" ).geocoded

    @geojson = build_geojson

    @tables_geo = @tables.map do |table|
      {
        lat: table.latitude,
        lng: table.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { table: table })
      }
    end
  end

  def user_index
    @tables = Table.where("userid = ?",current_user.id).geocoded
  end

  def show
    @table = Table.find(params[:id])
  end

  def create
    @table = Table.new(table_params)
    @table[:userid] = current_user.id
    if @table.save
      redirect_to user_index_path
    else
      flash[:notice] = "Table not saved. Description and location need to be atleast 10 characters long"
      render 'new'
    end
  end

  def new
    @table = Table.new
  end

  def edit
    @table = Table.find(params[:id])
  end

  def update
    @table = Table.find(params[:id])
    if @table.update(table_params)
      redirect_to user_index_path
    else
      flash[:notice] = "Table not updated. Description and location need to be atleast 10 characters long"
      render 'edit'
    end
  end

  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    redirect_to user_index_path
  end

  private

  def table_params
    params.require(:table).permit(:description, :location, :userid, :table_photo)
  end

  def build_geojson
    {
      type: "FeatureCollection",
      features: @tables.map(&:to_feature)
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/table_helper.rb
module TableHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/56d0a2f199.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@400;500&display=swap" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css" rel="stylesheet" />
    <title>RailsTableTennis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div><%= yield %></div>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-container">
    <div>
    <h5>Impressum</h5>
    </div>
    <div>
    <p>Janis Vaneylen</p>
    <p>Kremmener Str. 7, 10435 Berlin</p>
    <p>janis.vaneylen@gmail.com</p>
    </div>
    </div>
    <a href="https://github.com/Janis4411"><i class="fab fa-github"></i></a>
  <div>
    <%= image_tag('download.png', width: "60", height: "60", alt: 'Biomasa') %>
  </div>
  <div class="footer-copyright">
     <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-brand">
    <%= image_tag('download.png') %>
  </div>
    <div class="navbarheading" style="font-family: 'Montserrat Alternates', sans-serif">
      Berlin table tennis map
    </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if !user_signed_in? %>
      <li class="nav-item text-center">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item text-center">
        <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <div class="navbar-brand">
          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Show my tables", user_index_path, method: :get, class: "dropdown-item" %>
          <%= link_to "Add new table", new_table_path, method: :get, class: "dropdown-item" %>
          <%= link_to "Show Map", tables_path, method: :get, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tables/_form.html.erb
<div class="form_for">
  <%= form_for(@table) do |f| %>
    <div>
      <%= f.text_field :description, class: 'form-control form-control-lg', placeholder: "Table description", required: true %>
    </div>
      <div>
        <%= f.text_field :location, class: 'form-control form-control-lg', placeholder: "Table location", required: true %>
      </div>
      <div>
        <%= f.file_field :table_photo, direct_upload: true, class: 'form-control form-control-lg' %>
      </div>
    <div class="button">
      <%= f.submit :Submit, class: 'btn btn-dark btn-block' %>
    </div>
  <% end %>
</div>

app/views/tables/_info_window.html.erb
<% if table.table_photo.attached? %>
  <%= cl_image_tag table.table_photo.key, height: 150, width: 170, class: "mb-2", crop: :fill %>
<% end %>
<h2><%= table.description %></h2>
<p><%= table.location %></p>

app/views/tables/edit.html.erb
<div class="container">
  <div class="card">

    <h2>Edit table</h2>

    <%= render "form", table: @table %>
  </div>
</div>

app/views/tables/index.html.erb
<div id="map"
     style="width: 100%; height: 680px; padding: 0px"
     data-tables="<%= @geojson.to_json %>"
     data-mapbox-api-key="<%= AUTH_DETAILS['api_key'] %>">
</div>

app/views/tables/new.html.erb
<div class="container">
  <div class="card">

    <h2>Add new table</h2>

    <%= render "form", table: @table %>
  </div>
</div>

app/views/tables/user_index.html.erb
 <div class="row-container d-flex justify-content-center">
  <div>
  <h1 class="text-center">Your Tables</h1>
  <% if @tables.empty?  %>
    <h5>You have not posted any tables yet, go ahead!</h5>
  <% else %>
    <% @tables.each do |table| %>
      <div class="card" style="width: 18rem; margin: 10px;">
        <% if table.table_photo.attached? %>
          <%= cl_image_tag table.table_photo.key, height: 300, width: 150, class: "card-img-top p-2" %>
        <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= table.description %></h5>
        <p class="card-text"><%= table.location %></p>
      </div>
        <div class="card-body">
          <i class="fas fa-pencil-alt">
          <%= link_to "Edit Table",
                edit_table_path(table),
                data: { confirm: "Are you sure?" } %>
          </i>
          <i class="fas fa-trash-alt">
          <%= link_to "Delete table",
                table_path(table),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
          </i>
        </div>
      </div>
    <% end %>
  <% end  %>
  </div>
</div>